
# Build rules for objects
-include $(OBJECTS:.lo=.d)

# Special dependency for SDL.c, since it depends on SDL_revision.h
/Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL.c: update-revision

$(objects)/SDL.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_assert.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL_assert.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_error.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL_error.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_hints.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL_hints.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_log.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/SDL_log.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_atomic.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/atomic/SDL_atomic.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_spinlock.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/atomic/SDL_spinlock.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_audio.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_audio.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_audiocvt.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_audiocvt.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_audiodev.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_audiodev.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_audiotypecvt.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_audiotypecvt.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_mixer.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_mixer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_wave.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/SDL_wave.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cpuinfo.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/cpuinfo/SDL_cpuinfo.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_dynapi.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/dynapi/SDL_dynapi.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_clipboardevents.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_clipboardevents.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_dropevents.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_dropevents.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_events.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_events.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_gesture.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_gesture.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_keyboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_keyboard.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_mouse.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_mouse.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_quit.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_quit.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_touch.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_touch.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_windowevents.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/events/SDL_windowevents.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_rwops.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/file/SDL_rwops.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_haptic.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/haptic/SDL_haptic.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_gamecontroller.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/joystick/SDL_gamecontroller.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_joystick.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/joystick/SDL_joystick.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/e_atan2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/e_atan2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/e_log.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/e_log.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/e_pow.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/e_pow.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/e_rem_pio2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/e_rem_pio2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/e_sqrt.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/e_sqrt.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/k_cos.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/k_cos.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/k_rem_pio2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/k_rem_pio2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/k_sin.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/k_sin.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_atan.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_atan.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_copysign.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_copysign.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_cos.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_cos.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_fabs.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_fabs.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_floor.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_floor.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_scalbn.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_scalbn.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/s_sin.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/libm/s_sin.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_power.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/power/SDL_power.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_d3dmath.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/SDL_d3dmath.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/SDL_render.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_yuv_mmx.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/SDL_yuv_mmx.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_yuv_sw.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/SDL_yuv_sw.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_d3d.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/direct3d/SDL_render_d3d.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_d3d11.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/direct3d11/SDL_render_d3d11.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_gl.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/opengl/SDL_render_gl.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_shaders_gl.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/opengl/SDL_shaders_gl.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_gles.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/opengles/SDL_render_gles.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_gles2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/opengles2/SDL_render_gles2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_shaders_gles2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/opengles2/SDL_shaders_gles2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_psp.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/psp/SDL_render_psp.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blendfillrect.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_blendfillrect.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blendline.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_blendline.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blendpoint.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_blendpoint.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_drawline.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_drawline.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_drawpoint.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_drawpoint.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_render_sw.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_render_sw.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_rotate.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/render/software/SDL_rotate.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_getenv.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_getenv.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_iconv.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_iconv.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_malloc.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_malloc.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_qsort.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_qsort.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_stdlib.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_stdlib.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_string.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/stdlib/SDL_string.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_thread.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/SDL_thread.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_timer.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/timer/SDL_timer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_RLEaccel.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_RLEaccel.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_0.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_0.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_1.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_1.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_A.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_A.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_N.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_N.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_auto.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_auto.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_copy.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_copy.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_blit_slow.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_blit_slow.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_bmp.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_bmp.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_clipboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_clipboard.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_egl.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_egl.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_fillrect.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_fillrect.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_pixels.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_pixels.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_rect.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_rect.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_shape.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_shape.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_stretch.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_stretch.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_surface.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_surface.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_video.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/SDL_video.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_nullevents.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/dummy/SDL_nullevents.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_nullframebuffer.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/dummy/SDL_nullframebuffer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_nullvideo.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/dummy/SDL_nullvideo.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_diskaudio.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/disk/SDL_diskaudio.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_dummyaudio.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/dummy/SDL_dummyaudio.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_sysloadso.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/loadso/dlopen/SDL_sysloadso.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoaclipboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoaclipboard.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoaevents.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoaevents.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoakeyboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoakeyboard.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoamessagebox.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoamessagebox.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoamodes.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoamodes.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoamouse.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoamouse.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoamousetap.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoamousetap.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoaopengl.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoaopengl.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoashape.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoashape.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoavideo.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoavideo.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_cocoawindow.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/cocoa/SDL_cocoawindow.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11clipboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11clipboard.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11dyn.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11dyn.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11events.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11events.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11framebuffer.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11framebuffer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11keyboard.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11keyboard.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11messagebox.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11messagebox.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11modes.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11modes.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11mouse.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11mouse.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11opengl.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11opengl.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11opengles.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11opengles.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11shape.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11shape.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11touch.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11touch.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11video.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11video.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11window.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11window.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_x11xinput2.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/SDL_x11xinput2.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/edid-parse.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/edid-parse.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/imKStoUCS.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/video/x11/imKStoUCS.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_systhread.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/pthread/SDL_systhread.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_syssem.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/pthread/SDL_syssem.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_sysmutex.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/pthread/SDL_sysmutex.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_syscond.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/pthread/SDL_syscond.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_systls.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/thread/pthread/SDL_systls.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_coreaudio.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/audio/coreaudio/SDL_coreaudio.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_sysjoystick.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/joystick/darwin/SDL_sysjoystick.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_syshaptic.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/haptic/darwin/SDL_syshaptic.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_syspower.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/power/macosx/SDL_syspower.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_sysfilesystem.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/filesystem/cocoa/SDL_sysfilesystem.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_systimer.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/timer/unix/SDL_systimer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_rwopsbundlesupport.lo: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/file/cocoa/SDL_rwopsbundlesupport.m
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@


$(objects)/SDL_dummy_main.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/main/dummy/SDL_dummy_main.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@

$(objects)/SDL_test_assert.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_assert.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_common.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_common.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_compare.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_compare.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_crc32.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_crc32.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_font.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_font.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_fuzzer.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_fuzzer.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_harness.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_harness.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_imageBlit.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_imageBlit.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_imageBlitBlend.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_imageBlitBlend.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_imageFace.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_imageFace.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_imagePrimitives.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_imagePrimitives.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_imagePrimitivesBlend.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_imagePrimitivesBlend.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_log.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_log.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_md5.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_md5.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@ 
$(objects)/SDL_test_random.o: /Volumes/Data/nfs/zfs-student-4/users/2013_paris/tlloancy/projects/ok/ext/SDL2/SDL2-2.0.3/src/test/SDL_test_random.c
	$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(EXTRA_CFLAGS) -MMD -MT $@ -c $< -o $@
